name: Express CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Express app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            cd bixoquest
            cd bixoquest-backend
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            npm install
            pm2 restart bixoquest-backend
